version: "3"

services:

  db:
    container_name: db
    image: postgres:9.6.8-alpine
    ports:
      - '5432:5432'
    volumes:
      - ${DB_PATH}:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}

  test:
    command: sh -c 'sleep 3 && python -Wa manage.py test'
    container_name: tests
    image: gionn/blood-reminders:latest
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: db
      DB_PORT: '5432'