version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    environment:
      DB_NAME: test
      DB_USER: test
      DB_PASS: test
      DB_PATH: /dev/shm/pgdata

    steps:
      - checkout

      - run:
          name: Docker Hub login
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS

      - run:
          name: Build the docker image
          command: docker build -t gionn/blood-reminders:latest .

      - run:
          name: Run tests
          command: docker-compose -f docker-compose.test.yml up --abort-on-container-exit

      - run:
          name: Deploy image on Docker Hub if on master
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker push gionn/blood-reminders:latest
              docker tag gionn/blood-reminders:latest gionn/blood-reminders:$CIRCLE_BUILD_NUM
              docker push gionn/blood-reminders:$CIRCLE_BUILD_NUM
            fi
