# Generated by Django 2.0.1 on 2018-01-28 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('donation_type', models.CharField(blank=True, choices=[('B', 'Blood'), ('P', 'Plasma'), ('M', 'Multicomponent')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tax_code', models.CharField(max_length=16, unique=True)),
                ('born_date', models.DateField(default='1970-01-01')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('', 'undefined')], max_length=1)),
                ('last_donation_type', models.CharField(blank=True, choices=[('B', 'Blood'), ('P', 'Plasma'), ('M', 'Multicomponent')], max_length=1)),
                ('blood_type', models.CharField(blank=True, choices=[('O', 'O'), ('AB', 'AB'), ('A', 'A'), ('B', 'B')], max_length=2, null=True)),
                ('blood_rh', models.CharField(blank=True, choices=[('+', 'Positive'), ('-', 'Negative'), ('', 'undefined')], max_length=1, null=True)),
                ('last_donation_date', models.DateField(blank=True, default='1970-01-01', null=True)),
                ('suspension_date', models.DateField(blank=True, null=True)),
                ('suspension_reason', models.CharField(blank=True, max_length=512)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reminders.Donor')),
            ],
        ),
        migrations.AddField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reminders.Donor'),
        ),
    ]
