# Generated by Django 2.0.1 on 2018-01-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='email',
            field=models.CharField(default='noemail@example.org', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donor',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Undefined')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donor',
            name='last_donation_type',
            field=models.CharField(choices=[('S', 'Sangue Intero'), ('P', 'Plasmaferesi'), ('M', 'Multicomponent')], default='S', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donor',
            name='phone',
            field=models.CharField(default='0123456789', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donor',
            name='tax_code',
            field=models.CharField(default='TRL', max_length=16),
            preserve_default=False,
        ),
    ]
