# Generated by Django 2.0.1 on 2018-02-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='email',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='donor',
            name='phone',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
