# Generated by Django 2.0.1 on 2018-05-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_auto_20180211_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='address_city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='donor',
            name='address_postal_code',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='donor',
            name='address_province_code',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='donor',
            name='address_state',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='donor',
            name='address_street',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='donor',
            name='enrollment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='national_card_number',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
