# Generated by Django 2.0.1 on 2018-01-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_auto_20180113_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='last_donation_type',
            field=models.CharField(blank=True, choices=[('S', 'Sangue Intero'), ('P', 'Plasmaferesi'), ('M', 'Multicomponent')], max_length=1),
        ),
    ]
