# Generated by Django 3.0.4 on 2020-03-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0003_auto_20200328_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='exp',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
