# Generated by Django 3.1.2 on 2021-01-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0003_auto_20200328_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='last_donation_type',
            field=models.CharField(blank=True, choices=[('B', 'Blood'), ('P', 'Plasma'), ('M', 'Multicomponent')], max_length=1, null=True, verbose_name='last donation'),
        ),
    ]
