# Generated by Django 2.0.1 on 2018-01-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0004_auto_20180113_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donation_type',
            field=models.CharField(blank=True, choices=[('S', 'Sangue Intero'), ('P', 'Plasmaferesi'), ('M', 'Multicomponent')], max_length=1),
        ),
    ]
