# Generated by Django 2.0.1 on 2018-01-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0005_donation_donation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='born_date',
            field=models.DateTimeField(default='1970-01-01 00:00'),
        ),
    ]
