# Generated by Django 2.0.1 on 2018-01-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0006_donor_born_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='last_donation_date',
            field=models.DateField(blank=True, default='1970-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='born_date',
            field=models.DateField(default='1970-01-01'),
        ),
    ]
