# Generated by Django 2.0.1 on 2018-01-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0007_auto_20180121_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='suspension_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='suspension_reason',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
