# Generated by Django 2.0.1 on 2018-01-28 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0009_reminder_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='blood_rh',
            field=models.CharField(blank=True, choices=[('+', 'Positive'), ('-', 'Negative'), ('', 'undefined')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('O', 'O'), ('AB', 'AB'), ('A', 'A'), ('B', 'B')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('', 'undefined')], max_length=1),
        ),
        migrations.AlterField(
            model_name='donor',
            name='last_donation_type',
            field=models.CharField(blank=True, choices=[('B', 'Blood'), ('P', 'Plasma'), ('M', 'Multicomponent')], max_length=1),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
